### ISSUE TITLE
Build failure on Linux

### ISSUE THREAD

**Issue by SteveFosdick** [tom-seddon/b2#3]
Attempting to build master from github (0.0.4-120-g699023b) fails with this error:
```
FAILED: src/b2/CMakeFiles/test_JobQueue.dir/JobQueue.cpp.o 
/usr/bin/c++  -D_GNU_SOURCE -I../src/shared/h -save-temps -O2 -g -DNDEBUG   -Wall -Wuninitialized -Winit-self -pedantic -Werror=implicit-function-declaration -Wsign-conversion -Wunused-result -Wno-overlength-strings -Wunused-parameter -std=gnu++14 -MD -MT src/b2/CMakeFiles/test_JobQueue.dir/JobQueue.cpp.o -MF src/b2/CMakeFiles/test_JobQueue.dir/JobQueue.cpp.o.d -o src/b2/CMakeFiles/test_JobQueue.dir/JobQueue.cpp.o -c ../src/b2/JobQueue.cpp
../src/b2/JobQueue.cpp: In member function ‘bool JobQueue::Init(unsigned int)’:
../src/b2/JobQueue.cpp:110:41: error: ‘bind’ is not a member of ‘std’
             td->thread=std::thread(std::bind(&JobQueue::ThreadFunc,this,td));
                                         ^~~~
```

There are also some compiler warnings:
```
../submodules/SDL/src/render/opengles/SDL_render_gles.c: In function ‘GLES_CreateRenderer’:
../submodules/SDL/src/render/opengles/SDL_render_gles.c:347:30: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
     renderer->RenderGeometry = GLES_RenderGeometry;
                              ^
[63/302] Building C object submodules/...ir/src/render/opengl/SDL_render_gl.c.o
../submodules/SDL/src/render/opengl/SDL_render_gl.c: In function ‘GL_CreateRenderer’:
../submodules/SDL/src/render/opengl/SDL_render_gl.c:528:34: warning: pointer targets in assignment differ in signedness [-Wpointer-sign]
         shading_language_version = data->glGetString(GL_SHADING_LANGUAGE_VERSION);
                                  ^
[64/302] Building C object submodules/.../render/opengles2/SDL_render_gles2.c.o
../submodules/SDL/src/render/opengles2/SDL_render_gles2.c: In function ‘GLES2_RenderGeometry’:
../submodules/SDL/src/render/opengles2/SDL_render_gles2.c:2071:13: warning: ‘sourceType’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         if (GLES2_SelectProgram(renderer, sourceType, GLES2_SHADER_VERTEX_GEOMETRY) < 0 )
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[181/302] Building CXX object src/shared/t/CMakeFiles/test_basic.dir/test_basic.cpp.o
../src/shared/t/test_basic.cpp: In function ‘int main()’:
../src/shared/t/test_basic.cpp:136:15: warning: ‘%zu’ directive output truncated writing 5 bytes into a region of size 3 [-Wformat-truncation=]
     n=snprintf(buf,sizeof buf,"%zu",value);
       ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/shared/t/test_basic.cpp:136:15: note: ‘snprintf’ output 6 bytes into a destination of size 3
../src/shared/t/test_basic.cpp:206:5: warning: ‘%zx’ directive output truncated writing 4 bytes into a region of size 3 [-Wformat-truncation=]
 int main(void) {
     ^~~~
../src/shared/t/test_basic.cpp:144:13: note: ‘snprintf’ output 5 bytes into a destination of size 3
     snprintf(buf,sizeof buf,"%zx",value);
     ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
[204/302] Building CXX object experimental/test_dear_i...i/CMakeFiles/test_dear_imgui.dir/test_dear_imgui.cpp.o
In file included from ../submodules/imgui/./addons/imgui_user.h:130:0,
                 from ../submodules/imgui/imgui_user.h:9,
                 from ../submodules/imgui/imgui.h:1533,
                 from ../experimental/test_dear_imgui/test_dear_imgui.cpp:10:
../submodules/imgui/./addons/./imguitabwindow/imguitabwindow.h: In member function ‘void ImGui::TabWindow::TabLabel::setLabel(const char*, bool)’:
../submodules/imgui/./addons/./imguitabwindow/imguitabwindow.h:308:43: warning: conversion to ‘size_t {aka long unsigned int}’ from ‘int’ may change the sign of the result [-Wsign-conversion]
         label = (char*) ImGui::MemAlloc(sz+1);strcpy(label,lbl);
                                         ~~^~
In file included from ../submodules/imgui/./addons/imgui_user.h:130:0,
                 from ../submodules/imgui/imgui_user.h:9,
                 from ../submodules/imgui/imgui.h:1533,
                 from ../experimental/test_dear_imgui/test_dear_imgui.cpp:10:
../submodules/imgui/./addons/./imguitabwindow/imguitabwindow.h: In member function ‘void ImGui::TabWindow::TabLabel::setTooltip(const char*)’:
../submodules/imgui/./addons/./imguitabwindow/imguitabwindow.h:326:45: warning: conversion to ‘size_t {aka long unsigned int}’ from ‘int’ may change the sign of the result [-Wsign-conversion]
         tooltip = (char*) ImGui::MemAlloc(sz+1);strcpy(tooltip,tt);
                                           ~~^~
In file included from ../submodules/imgui/./addons/imgui_user.h:130:0,
                 from ../submodules/imgui/imgui_user.h:9,
                 from ../submodules/imgui/imgui.h:1533,
                 from ../experimental/test_dear_imgui/test_dear_imgui.cpp:10:
../submodules/imgui/./addons/./imguitabwindow/imguitabwindow.h: In member function ‘void ImGui::TabWindow::TabLabel::setUserText(const char*)’:
../submodules/imgui/./addons/./imguitabwindow/imguitabwindow.h:332:50: warning: conversion to ‘size_t {aka long unsigned int}’ from ‘int’ may change the sign of the result [-Wsign-conversion]
             userText = (char*) ImGui::MemAlloc(sz+1);strcpy(userText,_userText);
                                                ~~^~
In file included from ../submodules/imgui/./addons/imgui_user.h:181:0,
                 from ../submodules/imgui/imgui_user.h:9,
                 from ../submodules/imgui/imgui.h:1533,
                 from ../experimental/test_dear_imgui/test_dear_imgui.cpp:10:
../submodules/imgui/./addons/./imguitoolbar/imguitoolbar.h: In member function ‘size_t ImGui::Toolbar::getNumButtons() const’:
../submodules/imgui/./addons/./imguitoolbar/imguitoolbar.h:296:61: warning: conversion to ‘size_t {aka long unsigned int}’ from ‘int’ may change the sign of the result [-Wsign-conversion]
     inline size_t getNumButtons() const {return buttons.size();}
                                                 ~~~~~~~~~~~~^~
In file included from ../submodules/imgui/./addons/imgui_user.h:187:0,
                 from ../submodules/imgui/imgui_user.h:9,
                 from ../submodules/imgui/imgui.h:1533,
                 from ../experimental/test_dear_imgui/test_dear_imgui.cpp:10:
../submodules/imgui/./addons/./imguivariouscontrols/imguivariouscontrols.h: In static member function ‘static void ImGui::TreeViewNode::Data::SetString(char*&, const char*, bool)’:
../submodules/imgui/./addons/./imguivariouscontrols/imguivariouscontrols.h:539:54: warning: conversion to ‘size_t {aka long unsigned int}’ from ‘int’ may change the sign of the result [-Wsign-conversion]
                 destText = (char*) ImGui::MemAlloc(sz+1);strcpy(destText,text);
                                                    ~~^~
In file included from ../submodules/imgui/./addons/imgui_user.h:187:0,
                 from ../submodules/imgui/imgui_user.h:9,
                 from ../submodules/imgui/imgui.h:1533,
                 from ../experimental/test_dear_imgui/test_dear_imgui.cpp:10:
../submodules/imgui/./addons/./imguivariouscontrols/imguivariouscontrols.h: In member function ‘unsigned int ImGui::TreeViewNode::getMode() const’:
../submodules/imgui/./addons/./imguivariouscontrols/imguivariouscontrols.h:675:56: warning: conversion to ‘unsigned int’ from ‘int’ may change the sign of the result [-Wsign-conversion]
         if (m==MODE_NONE) m = MODE_INTERMEDIATE;return m;
                                                        ^
../experimental/test_dear_imgui/test_dear_imgui.cpp: In member function ‘bool Window::Init()’:
../experimental/test_dear_imgui/test_dear_imgui.cpp:248:9: warning: variable ‘rc’ set but not used [-Wunused-but-set-variable]
     int rc;
         ^~
../experimental/test_dear_imgui/test_dear_imgui.cpp: In member function ‘void Window::RenderImGuiDrawData()’:
../experimental/test_dear_imgui/test_dear_imgui.cpp:460:9: warning: variable ‘rc’ set but not used [-Wunused-but-set-variable]
     int rc;
         ^~
[206/302] Building CXX object src/6502/CMakeFiles/6502_gen.dir/6502_gen.cpp.o
../src/6502/6502_gen.cpp: In member function ‘void InstrGen::GeneratePhase1(const Cycle*) const’:
../src/6502/6502_gen.cpp:671:14: warning: variable ‘set_acarry’ set but not used [-Wunused-but-set-variable]
         bool set_acarry=false;
              ^~~~~~~~~~
```

**Comment by tom-seddon** [comment]
Ugh... it builds on my Ubuntu PC, and I get a slightly different set of warnings. What standard library and/or compiler are you using?

But anyway, I think the JobQueue.cpp problem might be a missing `#include <functional>`, so I've added that. I also fixed a number of the warnings in the emulator code.

**Comment by SteveFosdick** [comment]
Tom, it's Arch Linux so a rolling release and this no version number but gcc is 7.2.1 20171128.  I am not sure how to get the version number of the standard C++ library from within it but the package claims libstdc++5-3.3.6-5-x86_64.pkg.tar.xz

I'll try rebuilding after the changes you have made.

**Comment by SteveFosdick** [comment]
It still fails.  The errors are:

```
[254/302] Building CXX object src/b2/CMakeFiles/b2.dir/BeebWindows.cpp.o
FAILED: src/b2/CMakeFiles/b2.dir/BeebWindows.cpp.o 
/usr/bin/c++  -DBUILD_TYPE_RelWithDebInfo=1 -DHAVE_FFMPEG=1 -DIMGUI_INCLUDE_IMGUI_USER_H -DIMGUI_INCLUDE_IMGUI_USER_INL -DNO_IMGUI_ADDONS -DRMT_ENABLED=0 -DRMT_USE_D3D11=0 -DRMT_USE_OPENGL=0 -DUSING_GENERATED_CONFIG_H -DYES_IMGUIDOCK -DYES_IMGUIHELPER -DYES_IMGUIPANELMANAGER -DYES_IMGUITABWINDOW -DYES_IMGUITOOLBAR -D_GNU_SOURCE -Isubmodules/SDL/include -I../src/beeb/include -I../src/shared/h -I../src/6502/h -I../submodules/miniz -I../submodules/Remotery/lib -I../submodules/imgui -I../submodules/noc -I/usr/include/gtk-2.0 -I/usr/include/freetype2 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/atk-1.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/lib64/gtk-2.0/include -I../submodules/rapidjson/include -I../submodules/IconFontCppHeaders -save-temps -O2 -g -DNDEBUG   -Wall -Wuninitialized -Winit-self -pedantic -Werror=implicit-function-declaration -Wsign-conversion -Wunused-result -Wno-overlength-strings -Wunused-parameter -std=gnu++14 -MD -MT src/b2/CMakeFiles/b2.dir/BeebWindows.cpp.o -MF src/b2/CMakeFiles/b2.dir/BeebWindows.cpp.o.d -o src/b2/CMakeFiles/b2.dir/BeebWindows.cpp.o -c ../src/b2/BeebWindows.cpp
In file included from ../src/b2/BeebWindows.cpp:2:0:
../src/b2/BeebWindows.h:100:52: error: ‘function’ in namespace ‘std’ does not name a template type
     const BeebKeymap *ForEachBeebKeymap(const std::function<bool(const BeebKeymap *,BeebKeymap *)> &func);
                                                    ^~~~~~~~
../src/b2/BeebWindows.h:100:60: error: expected ‘,’ or ‘...’ before ‘<’ token
     const BeebKeymap *ForEachBeebKeymap(const std::function<bool(const BeebKeymap *,BeebKeymap *)> &func);
                                                            ^
In file included from ../src/b2/BeebWindows.cpp:2:0:
../src/b2/BeebWindows.h:134:35: error: ‘function’ in namespace ‘std’ does not name a template type
     void ForEachConfig(const std::function<bool(BeebConfig *,const BeebLoadedConfig *)> &func);
                                   ^~~~~~~~
../src/b2/BeebWindows.h:134:43: error: expected ‘,’ or ‘...’ before ‘<’ token
     void ForEachConfig(const std::function<bool(BeebConfig *,const BeebLoadedConfig *)> &func);
                                           ^
../src/b2/BeebWindows.cpp: In function ‘const BeebConfig* FindBeebConfigByName(const string&)’:
../src/b2/BeebWindows.cpp:148:6: error: cannot convert ‘FindBeebConfigByName(const string&)::<lambda(const BeebConfig*, const BeebLoadedConfig*)>’ to ‘int’ for argument ‘1’ to ‘void BeebWindows::ForEachConfig(int)’
     });
      ^
../src/b2/BeebWindows.cpp: At global scope:
../src/b2/BeebWindows.cpp:425:114: error: ‘const BeebKeymap* BeebWindows::ForEachBeebKeymap(const std::function<bool(const BeebKeymap*, BeebKeymap*)>&)’ should have been declared inside ‘BeebWindows’
 const BeebKeymap *BeebWindows::ForEachBeebKeymap(const std::function<bool(const BeebKeymap *,BeebKeymap *)> &func) {
                                                                                                                  ^
../src/b2/BeebWindows.cpp: In function ‘const BeebKeymap* BeebWindows::FindBeebKeymapByName(const string&)’:
../src/b2/BeebWindows.cpp:453:6: error: cannot convert ‘BeebWindows::FindBeebKeymapByName(const string&)::<lambda(const BeebKeymap*, BeebKeymap*)>’ to ‘int’ for argument ‘1’ to ‘const BeebKeymap* BeebWindows::ForEachBeebKeymap(int)’
     });
      ^
../src/b2/BeebWindows.cpp: At global scope:
../src/b2/BeebWindows.cpp:566:103: error: ‘void BeebWindows::ForEachConfig(const std::function<bool(BeebConfig*, const BeebLoadedConfig*)>&)’ should have been declared inside ‘BeebWindows’
 void BeebWindows::ForEachConfig(const std::function<bool(BeebConfig *,const BeebLoadedConfig *)> &func) {
                                                                                                       ^
```

On the warnings front there is:
```
[172/302] Building CXX object src/shared/CMakeFiles/shared_lib.dir/c/path.cpp.o
../src/shared/c/path.cpp: In function ‘bool PathLoadBinaryFile(std::vector<unsigned char>*, const string&)’:
../src/shared/c/path.cpp:202:18: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if(len<0||len>SIZE_MAX) {

[185/302] Building CXX object src/shared/t/CMakeFiles/test_basic.dir/test_basic.cpp.o
../src/shared/t/test_basic.cpp: In function ‘int main()’:
../src/shared/t/test_basic.cpp:136:15: warning: ‘%zu’ directive output truncated writing 5 bytes into a region of size 3 [-Wformat-truncation=]
     n=snprintf(buf,sizeof buf,"%zu",value);
       ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/shared/t/test_basic.cpp:136:15: note: ‘snprintf’ output 6 bytes into a destination of size 3
../src/shared/t/test_basic.cpp:206:5: warning: ‘%zx’ directive output truncated writing 4 bytes into a region of size 3 [-Wformat-truncation=]
 int main(void) {
     ^~~~
../src/shared/t/test_basic.cpp:144:13: note: ‘snprintf’ output 5 bytes into a destination of size 3
     snprintf(buf,sizeof buf,"%zx",value);
     ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

and then there are lots of the form:
```
[202/302] Building CXX object experimental/test_dear_imgui/CMakeFiles/test_dear_imgui.dir/imgui_node_graph_test_github.cpp.o
In file included from ../submodules/imgui/./addons/imgui_user.h:130:0,
                 from ../submodules/imgui/imgui_user.h:9,
                 from ../submodules/imgui/imgui.h:1533,
                 from ../experimental/test_dear_imgui/imgui_node_graph_test_github.cpp:2:
../submodules/imgui/./addons/./imguitabwindow/imguitabwindow.h: In member function ‘void ImGui::TabWindow::TabLabel::setLabel(const char*, bool)’:
../submodules/imgui/./addons/./imguitabwindow/imguitabwindow.h:308:43: warning: conversion to ‘size_t {aka long unsigned int}’ from ‘int’ may change the sign of the result [-Wsign-conversion]
         label = (char*) ImGui::MemAlloc(sz+1);strcpy(label,lbl);
                                         ~~^~
```

which I assume are a 32bit/64bit issue (I'm on 64bit).

**Comment by tom-seddon** [comment]
Thanks - I'll get myself set up with gcc 7 after Xmas. For now, I expect the problem is just another missing `#include <functional>` in `BeebWindows.h`. Looks like older gcc/clang aren't as thorough as they could be - though that's still more thorough than VC++... - about only exposing the minimum functionality in each header.

Once I'm up and running with gcc 7 I'll fix the printf warnings, which just need silencing. Regarding the dear imgui ones, they're just in some test code that can probably be deleted now...

**Comment by SteveFosdick** [comment]
#include <functional> in BeebWindows.h fixed the error.
